Feature/db setup
joshuaoivie/Vet-Clinic-DB pull request #1
Opened 2022-07-04 21:00 UTC by joshuaivie

Dear Code Reviewer,

This pull request contains the following changes:
1. Setup Database
2. Setup Animals Database
3. Populate the Animals with sample data
4. Perform the prescribed queries
5. Update README.

Here are the query results

Find all animals whose name ends in "mon."
![1](https://user-images.githubusercontent.com/28516413/177215786-ca052bbc-2934-4bd8-9daa-20020cdf264b.png)

List the name of all animals born between 2016 and 2019.
![2](https://user-images.githubusercontent.com/28516413/177215915-eedcd0a7-1d4b-484a-8ee9-cda8faf65bd7.png)

List the name of all animals that are neutered and have less than three escape attempts.
![3](https://user-images.githubusercontent.com/28516413/177215916-d1d4bb2e-2322-476c-ac0c-39c78bc82c19.png)

List the date of birth of all animals named "Agumon" or "Pikachu."
![4](https://user-images.githubusercontent.com/28516413/177215918-e994f632-4906-4cfb-a056-772171619646.png)

List name and escape attempts of animals that weigh more than 10.5kg.
![5](https://user-images.githubusercontent.com/28516413/177215919-329a8d6a-9a41-430c-afa5-e4ff360c4652.png)

Find all animals that are neutered.
![6](https://user-images.githubusercontent.com/28516413/177215920-1ed7588c-8f0a-4fde-b08e-520d0a3251ae.png)

Find all animals not named Gabumon.
![7](https://user-images.githubusercontent.com/28516413/177215921-90386fc9-29f3-4a54-abbe-fd0ec60267b3.png)

Find all animals with a weight between 10.4kg and 17.3kg (including the animals with weights that equals precisely 10.4kg or 17.3kg).
![8](https://user-images.githubusercontent.com/28516413/177215922-2c3539de-b0ab-4c74-b50a-860b08bc07e5.png)

Warm Regards,
Joshua Ivie.

2022-07-04 21:26 UTC, Davidosky007 requested changes
Hi @joshuaivie 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 21:26 UTC, Davidosky007 commented on queries.sql
> +select * from animals where name not like 'Gabumon';
* Kindly fix this `select * from animals where name not like 'Gabumon';` query result as when i ran the query this is what i get 
![image](https://user-images.githubusercontent.com/52497246/177217387-774a007d-1186-4ef2-b229-5287f9998118.png)

2022-07-04 21:26 UTC, Davidosky007 commented on queries.sql
> +select * from animals where name like '%mon';
* Kindly fix this query `select * from animals where name like '%mon';` as the result i get is not right 
![image](https://user-images.githubusercontent.com/52497246/177217795-5e8dd50f-57d3-4035-bfeb-a6169cbf13ad.png)

2022-07-09 23:47 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @joshuaivie, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- You did well to make the changes requested by the previous reviewer 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-10 00:44 UTC, merged